//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminSushiEntities : DbContext
    {
        public AdminSushiEntities()
            : base("name=AdminSushiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DIRECCION> DIRECCION { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<NIVELUSUARIO> NIVELUSUARIO { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
