//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public INVENTARIO()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal IDINVENTARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
