//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVELUSUARIO
    {
        public NIVELUSUARIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal IDNIVELUSUARIO { get; set; }
        public string NOMBRENIVELUSUARIO { get; set; }
        public string DESCRIPCIONNIVELUSUARIO { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
