//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal IDPEDIDO { get; set; }
        public decimal VALOR { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public string DETALLE { get; set; }
        public decimal DIRECCION_IDDIRECCION { get; set; }
        public decimal USUARIO_IDUSUARIO { get; set; }
    
        public virtual DIRECCION DIRECCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
