//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public decimal IDPRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal VALOR { get; set; }
        public Nullable<decimal> PEDIDO_IDPEDIDO { get; set; }
        public Nullable<decimal> INVENTARIO_IDINVENTARIO { get; set; }
    
        public virtual INVENTARIO INVENTARIO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
